#!/bin/bash
# Manual deployment commands for TiltCheck Server
# Copy and paste these commands one by one

echo "🚀 TiltCheck Manual Deployment Commands"
echo "======================================="
echo ""
echo "⚠️  HOSTNAME RESOLUTION ISSUE DETECTED"
echo "server1.tiltcheck.it.com is not resolving"
echo ""
echo "🔍 TROUBLESHOOTING STEPS:"
echo ""
echo "1a. Check if domain exists:"
echo "    nslookup server1.tiltcheck.it.com"
echo "    dig server1.tiltcheck.it.com"
echo ""
echo "1b. Try direct IP connection (if you have the IP):"
echo "    # Replace XXX.XXX.XXX.XXX with actual server IP"
echo "    sshpass -p 'iVjgB6BM' ssh -p 6467 kvmnode202@XXX.XXX.XXX.XXX"
echo ""
echo "1c. Check if it's a subdomain issue - try:"
echo "    nslookup tiltcheck.it.com"
echo "    sshpass -p 'iVjgB6BM' ssh -p 6467 kvmnode202@tiltcheck.it.com"
echo ""
echo "1d. Original connection attempt:"
echo "    sshpass -p 'iVjgB6BM' ssh -p 6467 kvmnode202@server1.tiltcheck.it.com"
echo ""
echo "2. Install SSL Manager:"
echo "   curl -sL 'https://ssl-manager.s3.amazonaws.com/external/sh/installer.sh' | sh"
echo ""
echo "3. Register SSL Manager:"
echo "   echo 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzZmODYyN2ZjOGE1NjAwMWM3YzY3ZTQiLCJpYXQiOjE3MzUzMDA2NDcsImV4cCI6MTczNTkwNTQ0N30.m8VlRwSfUJmLFb4MWayJNJ0WLbT7p_FyggkdX4bH_iE' | ssl-manager register"
echo ""
echo "4. Update system:"
echo "   sudo apt update && sudo apt upgrade -y"
echo ""
echo "5. Install dependencies:"
echo "   sudo apt install -y nodejs npm nginx certbot python3-certbot-nginx"
echo ""
echo "6. Create project directory:"
echo "   mkdir -p ~/tiltcheck/{dashboard,security}"
echo ""
echo "7. Setup SSL certificate:"
echo "   sudo certbot --nginx -d server1.tiltcheck.it.com --non-interactive --agree-tos --email admin@tiltcheck.it.com"
echo ""
echo "8. Create simple overlay server:"
echo "   cat > ~/tiltcheck/dashboard/overlay.html << 'EOF'"
echo "<!DOCTYPE html>"
echo "<html><head><title>TiltCheck AIM Overlay</title></head>"
echo "<body><h1>TiltCheck AIM System Active</h1>"
echo "<script src='aim-messenger.js'></script></body></html>"
echo "EOF"
echo ""
echo "9. Start simple web server:"
echo "   cd ~/tiltcheck/dashboard && python3 -m http.server 8080 &"
echo ""
echo "10. Test access:"
echo "    curl http://localhost:8080"
echo ""
echo "✅ Basic deployment complete!"
echo "🌐 Access at: https://server1.tiltcheck.it.com:8080"
